// Generated by CoffeeScript 1.8.0
(function() {
  var Component;

  Component = (function() {
    function Component() {}

    return Component;

  })();

  module.exports = Component;

}).call(this);
