// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    Entity: require('Entity'),
    Component: require('Component'),
    System: require('System'),
    World: require('World')
  };

}).call(this);
