// Generated by CoffeeScript 1.8.0
(function() {
  var EventEmitter, Family, LinkedList, World, key, val, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  EventEmitter = require('events').EventEmitter;

  LinkedList = require('dll');

  Family = (function(_super) {
    __extends(Family, _super);

    function Family(components, world) {
      var entity, next;
      this.components = components;
      Family.__super__.constructor.call(this);
      world.on('entityComponentsChanged', this._onEntityComponentsChanged.bind(this));
      world.on('entityAdded', this._onEntityAdded.bind(this));
      world.on('entityRemoved', this._onEntityRemoved.bind(this));
      world.on('entitiesAdded', this._onEntitiesAdded.bind(this));
      world.on('entitiesRemoved', this._onEntitiesRemoved.bind(this));
      next = world.entities.first;
      while (next != null) {
        entity = next.obj;
        if (entity._components.has(this.components)) {
          this.add(entity);
        }
        next = next.next;
      }
      return;
    }

    Family.prototype._onEntityComponentsChanged = function(entity) {
      if (!this.contains(entity)) {
        if (entity._components.has(this.components)) {
          this.add(entity);
          this.emit('entityAdded', entity);
        }
      } else {
        if (!entity._components.has(this.components)) {
          this.remove(entity);
          this.emit('entityRemoved', entity);
        }
      }
    };

    Family.prototype._onEntityAdded = function(entity) {
      if (!entity._components.has(this.components)) {
        return;
      }
      this.add(entity);
      this.emit('entityAdded', entity);
    };

    Family.prototype._onEntityRemoved = function(entity) {
      if (!this.contains(entity)) {
        return;
      }
      this.remove(entity);
      this.emit('entityRemoved', entity);
    };

    Family.prototype._onEntitiesAdded = function(entities) {
      var entitiesAdded, entity, _i, _len;
      entitiesAdded = [];
      for (_i = 0, _len = entities.length; _i < _len; _i++) {
        entity = entities[_i];
        if (entity._components.has(this.components)) {
          this.add(entity);
          entitiesAdded.push(entity);
        }
      }
      if (entitiesAdded.length > 0) {
        this.emit('entitiesAdded', entitiesAdded);
      }
    };

    Family.prototype._onEntitiesRemoved = function(entities) {
      var entitiesRemoved, entity, _i, _len;
      entitiesRemoved = [];
      for (_i = 0, _len = entities.length; _i < _len; _i++) {
        entity = entities[_i];
        this.remove(entity);
        entitiesRemoved.push(entity);
      }
      if (entitiesRemoved.length > 0) {
        this.emit('entitiesRemoved', entitiesRemoved);
      }
    };

    return Family;

  })(LinkedList);

  _ref = EventEmitter.prototype;
  for (key in _ref) {
    if (!__hasProp.call(_ref, key)) continue;
    val = _ref[key];
    if (Family.prototype[key] == null) {
      Family.prototype[key] = val;
    }
  }

  World = (function(_super) {
    __extends(World, _super);

    World._bm = require('bm')(1000);

    function World() {
      World.__super__.constructor.apply(this, arguments);
      this.entities = new LinkedList;
      this.systems = new LinkedList;
      this._families = {};
      this._onComponentsChanged = this._onComponentsChanged.bind(this);
    }

    World.prototype.add = function(entity) {
      if (this.entities.contains(entity)) {
        return entity;
      }
      this.entities.add(entity);
      entity.on('componentsAdded', this._onComponentsChanged);
      entity.on('componentsRemoved', this._onComponentsChanged);
      this.emit('entityAdded', entity);
      return entity;
    };

    World.prototype.addAll = function(entities) {
      var entity, _i, _len;
      for (_i = 0, _len = entities.length; _i < _len; _i++) {
        entity = entities[_i];
        if (this.entities.contains(entity)) {
          continue;
        }
        this.entities.add(entity);
        entity.on('componentsAdded', this._onComponentsChanged);
        entity.on('componentsRemoved', this._onComponentsChanged);
      }
      this.emit('entitiesAdded', entities);
    };

    World.prototype.remove = function(entity) {
      if (!this.entities.remove(entity)) {
        return false;
      }
      entity.removeListener('componentsAdded', this._onComponentsChanged);
      entity.removeListener('componentsRemoved', this._onComponentsChanged);
      this.emit('entityRemoved', entity);
      return true;
    };

    World.prototype.removeAll = function(entities) {
      var entity, _i, _len;
      for (_i = 0, _len = entities.length; _i < _len; _i++) {
        entity = entities[_i];
        if (!this.entities.remove(entity)) {
          continue;
        }
        entity.removeListener('componentsAdded', this._onComponentsChanged);
        entity.removeListener('componentsRemoved', this._onComponentsChanged);
      }
      this.emit('entitiesRemoved', entities);
      return entities;
    };

    World.prototype.addSystem = function(system) {
      if (this.systems.contains(system)) {
        return system;
      }
      this.systems.add(system);
      if (typeof system.init === "function") {
        system.init(this);
      }
      return system;
    };

    World.prototype.invoke = function() {
      var args, name, next, _base;
      name = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      next = this.systems.first;
      while (next != null) {
        if (typeof (_base = next.obj)[name] === "function") {
          _base[name].apply(_base, args);
        }
        next = next.next;
      }
    };

    World.prototype.get = function() {
      var mask, maskKey, _ref1;
      if (arguments.length === 0) {
        return void 0;
      }
      mask = World._bm.apply(World, arguments);
      maskKey = mask.toString();
      return (_ref1 = this._families[maskKey]) != null ? _ref1 : (this._families[maskKey] = new Family(mask, this));
    };

    World.prototype._onComponentsChanged = function(entity) {
      return this.emit('entityComponentsChanged', entity);
    };

    return World;

  })(EventEmitter);

  module.exports = World;

}).call(this);
